blog/urls.py
from django.urls import path
from django.views.generic import ListView, DetailView
from blog.models import Post

urlpatterns = [
    path('', ListView.as_view(queryset=Post.objects.all().order_by("-date")[:25], template_name = "blog/blog.html")),path('<int:pk>/',DetailView.as_view(model = Post, template_name = "blog/post.html"))
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('personal.urls')),
    path('blog/', include('blog.urls')),
    path('home/', include('personal.urls')),
    path('email/', include('sendemail.urls')),
    path('success/', include('sendemail.urls')),
    path('resume/', include('resume.urls')),
]

personal/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.index, name='index'),
]

resume/urls.py
from django.urls import path, include
from resume import views

urlpatterns = [
    path('', views.pdf_view, name='pdf'),
]

sendemail/urls.py
from django.contrib import admin
from django.urls import path

from .views import emailView, successView

urlpatterns = [
    path('', emailView, name='email'),
    path('success/', successView, name='success'),
]

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length = 140)
    body = models.TextField()
    date = models.DateTimeField()

    def __str__(self):
        return self.title

personal/models.py
from django.db import models

# Create your models here.

resume/models.py
from django.db import models

# Create your models here.

sendemail/models.py
from django.db import models

# Create your models here.

sendemail/forms.py
from django import forms

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

blog/views.py
from django.shortcuts import render

# Create your views here.

personal/views.py
from django.shortcuts import render

def index(request): 
    return render(request, 'personal/home.html')

resume/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

def pdf_view(request):
    with open('/home/rj/myprojectdir/resume/templates/resume/RichJoseph.pdf', 'rb') as pdf:
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'inline;filename=some_file.pdf'
        return response

sendemail/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm

def emailView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['richjoseph1129@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('success')
    return render(request, 'sendemail/email.html', {'form': form})

def successView(request):
    # return HttpResponse('Success! Thank you for your message.')
    return render(request, 'sendemail/success.html')

blog/templates/blog/blog.html
{% extends 'personal/header.html' %}
{% block extrahead%}
    {% load static %}    
    <link rel="stylesheet" type="text/css" href="{% static "blog/css/blog.css"%}">
{% endblock %}
{% block content %}
    <h1 class="pageTitle"> Posts <h1>
    {% for posts in object_list %}
        <div class="container">
            <div class="card">
                <div class="card-header"><a href="/blog/{{posts.id}}">{{posts.date|date:"Y-m-d"}}</a></div>
                <div class="card-body"><blockquote class="blockquote mb-0"><p>{{posts.title}}</p></blockquote></div>
            </div>
        </div>
    {% endfor %}
{% endblock %} 

blog/templates/blog/post.html
{% extends 'personal/header.html' %}
{% block extrahead%}
    {% load static %}    
    <link rel="stylesheet" type="text/css" href="{% static "blog/css/style.css"%}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="card">
            <h5 class="card-header">{{post.title}}</h5>
            <div class="card-body">
                <h5 class="card-title">{{post.date}}</h5>
                <p class="card-text">{{post.body|safe|linebreaks}}</p>
            </div>
        </div>
    </div>
{% endblock %} 

personal/templates/personal/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

{% comment %} Bootstrap CSS {% endcomment %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% comment %} google fonts {% endcomment %}
    <link href="https://fonts.googleapis.com/css?family=Oxygen:400,700&display=swap" rel="stylesheet">
{% comment %} font awesome {% endcomment %}
    <script src="https://kit.fontawesome.com/a364443456.js"></script>
{% comment %} stylesheet {% endcomment %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/personal/css/style.css' %}">

    {% block extrahead%}
    {% endblock%}
    <script src="/static/personal/js/main.js"></script>

    <title>Richard Joseph</title>

</head>
<body>
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <div class="container">
      <a class="navbar-brand" href="/home/"><span class="firstName">Richard</span><span class = "lastName"> Joseph</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="navbarNavDropdown" class="navbar-collapse collapse">
        <ul class="navbar-nav mr-auto">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/RichJ92"><span class="icon"><i class="fab fa-github"></i></span> GitHub</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/richard-joseph-600b53164/"><span class="icon"><i class="fab fa-linkedin-in"></i></span> LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/blog/"><span class="icon"><i class="fas fa-blog"></i></span> Posts</a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="/resume/"><span class="icon"><i class="fas fa-file"></i></span> Resume</a>
          </li>
        </ul>
        </ul>
          <ul class="navbar-nav ml-auto">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/email/"><span class="icon"><i class="fas fa-envelope"></i></span> Contact</a>
          </li>
        </ul>
      </div>
  </div>
</nav>

<div>
  {% block content%}
  {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

personal/templates/personal/home.html
{% extends 'personal/header.html' %}

{% block content %}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active image1"></div>
    <div class="carousel-item image2"></div>
    <div class="carousel-item image3"></div>
    {% comment %} ABOUT {% endcomment %}
    <div class="about" class="container">
      <div class="row">
        <div class="col-lg-12">
          <div id="content">
            <h4 class="text-center">Computer Science Student at Oregon State University (Post-Bacc. Program)
            </h4>
            <hr style="background-color: white">
            <p class="text-center">Passionate about technology but more importantly I am passionate about
              learning. See my work below.</p>
            <div id="scroll-button" class="double-down-button" onclick="bottom();"><i
                class="fas fa-chevron-circle-down"></i></div>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>

  {% comment %} Background {% endcomment %}
  <div class="dark-back">
    <div class="container">
      <h4 id="my_background">My Background</h4>
      <p class="back-text">I am currently taking classes remotely at Oregon State University's Computer Science
        post-baccalaureate program. My first degree is in Biology from the University of Massachusetts
        Dartmouth.
        I have always been a curious person and a person that has been able to take the initiative. In this way
        I feel like a computer science degree has been right for me. What spurred me to do this program was
        my old job in assay development in which compiling and analyzing data was a crucial part in making the
        right decisions. The job taught me how to use excel in a more robust way and how to use minitab in a
        way that I have never done before. The use of these programs I guess introduced me to learning python so
        I could analyze data in a better way. I decided I liked to code but was it a career move that I wanted
        to make.
        To test the waters I took an online programming class at University of Massachusetts Dartmouth "Computer
        Program with C", after the end of the class I felt like enrolling in a computer science program was the
        right choice. This degree will supplement my biology degree by becoming more efficient and
        allowing me to look at data in different ways. The degree will also open more doors in my career in
        terms of different software engineering paths. </p>
    </div>
  </div>

  {% comment %} Projects {% endcomment %}
  <div class="container">
    <h4 id="projects">Projects</h4>
    <div class="table-wrapper-scroll-y my-custom-scrollbar">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Language</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><a href="https://github.com/RichJ92/Final-Project">CS 162 Final Project</a></td>
            <td>Final Project for CS 162. The task is to complete earn enough to buy the necessary items to
              leave. Train, scout, fight, repeat.</td>
            <td>C++</td>
          </tr>
          <tr>
            <td><a href="https://github.com/RichJ92/ZooTycoon/tree/master/ZooTycoon">Zoo Tycoon</a></td>
            <td>Virtual Zoo. That allows you to buy animals. Also prints
              out daily stats for each day. Keep your zoo afloat</td>
            <td>C++</td>
          </tr>
          <tr>
            <td><a href="https://github.com/RichJ92/langstonsAnt/tree/master/Langston's%20Ant">Langston's
                Ant</a></td>
            <td>Program that asks the user for rows and columns of board
              to construct. User is asked to input ants placement and direction
              alongside number of iterations. Langston's ant program starts and
              iterates</td>
            <td>C++</td>
          </tr>

        </tbody>
      </table>
    </div>

  </div>
  <br>
  <br>
  <br>
  {% endblock %}

personal/templates/personal/includes/htmlsnippet.html
{% block content %}
<p>Look at me I am included</p>
{% endblock  %}

sendemail/templates/sendemail/email.html
{% extends 'personal/header.html' %}

{% block extrahead%}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'sendemail/css/style.css'%}">
{% endblock %}

{% block content %}


<div class="container">

    <h1 class="text-center">Contact Me</h1>

  <form method="post" >
    {% csrf_token %}

    <label for="name">Name</label>
    <input type="text" id="name" name="name" placeholder="">

    <label for="id_from_email">Email address</label>
    <input type="email" id="id_from_email" name="from_email" placeholder="" required>

    <label for="id_subject">Reason</label>
    <select id="id_subject" name="subject">
      <option value="Career Opportunity">Career Opportunity</option>
      <option value="Code Improvement Suggestion">Suggestions for Code Improvements</option>
      <option value="Other">Other</option>
    </select>
    <label for="id_message">Message</label>
    <textarea type="text" id="id_message" name="message" placeholder="..." style="height:200px"></textarea>
      <div class="text-center" class="form-actions">
    <button class="btn btn-dark">Send</button>
  </form>
</div>
<br>
<br>
<p class="text-center">richjoseph1129@gmail.com      or      josephri@oregonstate.edu</p>
{% endblock %}

sendemail/templates/sendemail/success.html
{% extends 'personal/header.html' %}

{% block content %}
<h1 class="text-center" style="padding-top: 10%">Thank you for your message!</h1>
{% endblock %}